theme: jekyll-theme-cayman
title: Object Detection and Tracking with Autonomous Drones
description: Xinchao Song, James Ballow, Surendra Singh, Alif Jakir, Shuvangkar Das, Linh Vu, and Md Isfakul Anam, Clarkson University, Potsdam, NY
show_downloads: true